In [ ]:
# Importing all of the relevant programs we will need for this project. 
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt 
import csv 

# Reading in the data set and displaing the first 5 rows of the data set. 
# Fixed a UnicodeError: we used the csv module from Python to process the code line by line 
# without worrying about whether a row has 13, 14, or 17 fields 
# due to certain inconsistencies in the number of columns in some of the rows. 

df = pd.DataFrame(
    list(csv.reader(open("kickstarter.csv", encoding="utf-8")))
)

## Overview of the data frame, including the numeber of rows and columns, data types, and memory usage. 

display(df.head())
print("Dataset shape:", df.shape)
display(df.info())
display(df.describe(include="all").T)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
0,ID,name,category,main_category,currency,deadline,goal,launched,pledged,state,backers,country,usd pledged,NaN,NaN,NaN,NaN
1,1000002330,The Songs of Adelaide & Abullah,Poetry,Publishing,GBP,2015-10-09 11:36:00,1000,2015-08-11 12:12:28,0,failed,0,GB,0,NaN,NaN,NaN,NaN
2,1000004038,Where is Hank?,Narrative Film,Film & Video,USD,2013-02-26 00:20:50,45000,2013-01-12 00:20:50,220,failed,3,US,220,NaN,NaN,NaN,NaN
3,1000007540,ToshiCapital Rekordz Needs Help to Complete Album,Music,Music,USD,2012-04-16 04:24:11,5000,2012-03-17 03:24:11,1,failed,1,US,1,NaN,NaN,NaN,NaN
4,1000011046,Community Film Project: The Art of Neighborhoo...,Film & Video,Film & Video,USD,2015-08-29 01:00:00,19500,2015-07-04 08:35:03,1283,canceled,14,US,1283,NaN,NaN,NaN,NaN

Dataset shape: (323751, 17)
<class 'pandas.DataFrame'>
RangeIndex: 323751 entries, 0 to 323750
Data columns (total 17 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   0       323751 non-null  str
 1   1       323751 non-null  str
 2   2       323751 non-null  str
 3   3       323751 non-null  str
 4   4       323751 non-null  str
 5   5       323751 non-null  str
 6   6       323751 non-null  str
 7   7       323751 non-null  str
 8   8       323751 non-null  str
 9   9       323751 non-null  str
 10  10      323751 non-null  str
 11  11      323751 non-null  str
 12  12      323751 non-null  str
 13  13      625 non-null     str
 14  14      624 non-null     str
 15  15      624 non-null     str
 16  16      624 non-null     str
dtypes: str(17)
memory usage: 42.0 MB

None

     count  unique                       top    freq
0   323751  323751                       ID        1
1   323751  321617  New EP/Music Development      41
2   323751     772            Product Design   17477
3   323751     121              Film & Video   57679
4   323751      38                       USD  260298
5   323751  294814                       USD     508
6   323751    8189                      5000   25520
7   323751  322799                      5000      60
8   323751   55599                         0   45784
9   323751     411                    failed  168221
10  323751    3593                         0   48863
11  323751     163                        US  257565
12  323751   94378                         0   50462
13     625     416                         0     101
14     624       9                               612
15     624       4                               620
16     624       2                               623

In [31]:

df_clean = df.copy() 
df_clean = df_clean.dropna() # Drop rows with missing values. 
df.head() #Will stop here, and take a look at the summary statistics at a later time today!

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
0,ID,name,category,main_category,currency,deadline,goal,launched,pledged,state,backers,country,usd pledged,NaN,NaN,NaN,NaN
1,1000002330,The Songs of Adelaide & Abullah,Poetry,Publishing,GBP,2015-10-09 11:36:00,1000,2015-08-11 12:12:28,0,failed,0,GB,0,NaN,NaN,NaN,NaN
2,1000004038,Where is Hank?,Narrative Film,Film & Video,USD,2013-02-26 00:20:50,45000,2013-01-12 00:20:50,220,failed,3,US,220,NaN,NaN,NaN,NaN
3,1000007540,ToshiCapital Rekordz Needs Help to Complete Album,Music,Music,USD,2012-04-16 04:24:11,5000,2012-03-17 03:24:11,1,failed,1,US,1,NaN,NaN,NaN,NaN
4,1000011046,Community Film Project: The Art of Neighborhoo...,Film & Video,Film & Video,USD,2015-08-29 01:00:00,19500,2015-07-04 08:35:03,1283,canceled,14,US,1283,NaN,NaN,NaN,NaN